### ISSUE TITLE
Better closing and opening animations

### ISSUE THREAD

**Issue by erikinkinen** [cutie-shell/cutie-keyboard#1]
We need to bring back the old animations/transitions from the previous keyboard as the current ones feel clunky imho.

When the keyboard opens on focusing a text field, it should slide from the bottom of the screen to its open position. The application window should also be resizing in animated fashion to give space for the keyboard.

When dragging down, the keyboard should move down and resize the application to match the new position. When lifting the drag, the keyboard should either close or return to its previous position depending on a threshold. Both of these cases should result in a smooth animated transition of both the keyboard and the application window.

cc @arpio23

**Comment by arpio23** [comment]
This will be added when debian moves qt6.6 to testing or sid. Will be much easier as then we can control the layershell in qml.

**Comment by arpio23** [comment]
Need to test on different devices:
https://github.com/cutie-shell/cutie-wlc/commit/81ce6fca20c98e8589e689470e049b7ab2b53e33
https://github.com/cutie-shell/cutie-keyboard/commit/fcc7c74a3b5b3f9be3296048599a2754ba2a1d76

**Comment by erikinkinen** [comment]
Is this now fixed or are we still missing something?
